### ISSUE TITLE
layer 7 update

### ISSUE THREAD

**Issue by itzfoxii** [GBRodrickTed/Faster-Punch#2]
in the new update for layer 7 the mod makes you not punch at all with the feedbacker or knuckle blaster

**Comment by ERROR200013** [comment]
Same

**Comment by TinyDeskEngineer06** [comment]
Whiplash still works fine, just as it did before Layer 7 was released. It does, however, spam the console with errors. Not sure if that was the case before or not, never had any reason to look at the console while playing before this.

**Comment by GBRodrickTed** [comment]
I'll fix it soon

**Comment by itzfoxii** [comment]
when is soon

**Comment by GBRodrickTed** [comment]
probably before next year
